### ISSUE TITLE
Privacy Icon Doesn’t Appear for Mediated Yahoo Native Ads

### ISSUE THREAD

**Issue by stuartbreckenridge** [mopub/mopub-ios-mediation#63] opened 2018-05-27 00:39 UTC
Integrating following the instructions works for MoPub and Facebook ads, but for Yahoo the privacy icon doesn’t display. 
<img width="387" alt="aabd29cf-03af-40d5-8639-672acfebe0e1" src="https://user-images.githubusercontent.com/7046652/40581375-732e9ca6-6189-11e8-9209-52016558a7bb.png">
<img width="391" alt="c82ff574-d0e7-4ac1-83d8-6ee0aaa66b06" src="https://user-images.githubusercontent.com/7046652/40581376-735cab3c-6189-11e8-935c-2591577ccbc5.png">
<img width="384" alt="ed57f9d4-e40e-434f-a504-7da929a19685" src="https://user-images.githubusercontent.com/7046652/40581377-73973824-6189-11e8-83ed-c7f739fc2287.png">

**Comment by chauduyphanvu1** [comment] 2018-05-27 00:42
@stuartbreckenridge, did you try the instructions at the bottom of this page? It is added as a custom property in your implementation. https://developer.yahoo.com/flurry/docs/faq/faqpublisher/ios/#how-do-i-display-the-sponsored-icon-when-mediating-native-ads-with-mopub=

**Comment by stuartbreckenridge** [comment] 2018-05-27 00:48
I have. Whether I overrride the function or otherwise, the result remains the same, the icon isn’t there.

**Comment by stuartbreckenridge** [comment] 2018-05-27 05:16
Giving Flurry its own implementation of `MPNativeAdRendering` solved the problem.

**Comment by chauduyphanvu1** [comment] 2018-11-08 20:32
@stuartbreckenridge, could you attach a mini sample project that reproduces that? Thanks!

**Comment by stuartbreckenridge** [comment] 2018-11-09 00:44
I've created a sample project as requested. It can be forked from [this repo](https://github.com/stuartbreckenridge/flurry-example). 

# Summary

Below is the downloaded native ad with no Flurry privacy icon:

![simulator screen shot - iphone xr - 2018-11-09 at 08 31 08](https://user-images.githubusercontent.com/7046652/48235794-498b5f80-e3fa-11e8-85a3-045a5c1f4b2b.png)

This is the layout of the ad in storyboard (note: the privacy icon _is_ in the bottom right):

<img width="452" alt="screenshot 2018-11-09 at 8 32 46 am" src="https://user-images.githubusercontent.com/7046652/48235823-7770a400-e3fa-11e8-8efd-a75cd2893162.png">

The `AdView` code:

```swift

class AdView: UIView {

    @IBOutlet weak var adTitle: UILabel!
    @IBOutlet weak var adSponsor: UILabel!
    @IBOutlet weak var adIcon: UIImageView!
    @IBOutlet weak var adPrivacyIcon: UIImageView!
    
    override init(frame: CGRect) {
        super.init(frame: frame)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    static func nibForAd() -> UINib! {
        return UINib(nibName: "AdView", bundle: Bundle.main)
    }

}

extension AdView: MPNativeAdRendering {
    
    func nativeTitleTextLabel() -> UILabel! {
        return adTitle
    }
    
    func nativeIconImageView() -> UIImageView! {
        return adIcon
    }
    
    func nativePrivacyInformationIconImageView() -> UIImageView! {
        return adPrivacyIcon
    }
    
    func layoutCustomAssets(withProperties customProperties: [AnyHashable : Any]!, imageLoader: MPNativeAdRenderingImageLoader!) {
        guard let str = customProperties["flurry_secHqBrandingLogo"] as? String, let imageUrl = URL(string: str) else {
            return
        }
        imageLoader.loadImage(for: imageUrl, into: self.adPrivacyIcon)
        
        guard let source = customProperties["flurry_source"] as? String else {
            self.adSponsor.text = "Sponsored".uppercased()
            return
        }
        self.adSponsor.text = "Sponsored by \(source)".uppercased()
    }
}
```

Am I missing something obvious?!

**Comment by stuartbreckenridge** [comment] 2018-11-09 01:17
From what I can tell with breakpoints in the `MPStaticNativeAdRenderer` implementation, the code runs to _No privacy icon_, which makes sense given the visual behaviour:

```objc
if ([self.adView respondsToSelector:@selector(nativePrivacyInformationIconImageView)]) {
        UIImage *privacyIconImage = [adapter.properties objectForKey:kAdPrivacyIconUIImageKey];
        NSString *privacyIconImageUrl = [adapter.properties objectForKey:kAdPrivacyIconImageUrlKey];
        // A cached privacy information icon image exists; it should be used.
        if (privacyIconImage != nil) {
            UIImageView *imageView = self.adView.nativePrivacyInformationIconImageView;
            imageView.hidden = NO;
            imageView.image = privacyIconImage;

            // Attach a gesture recognizer to handle loading the privacy icon URL.
            UITapGestureRecognizer *tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(onPrivacyIconTapped)];
            imageView.userInteractionEnabled = YES;
            [imageView addGestureRecognizer:tapRecognizer];
        }
        // No cached privacy information icon image was cached, but there is a URL for the
        // icon. Go fetch the icon and populate the UIImageView when complete.
        else if (privacyIconImageUrl != nil) {
            NSURL *iconUrl = [NSURL URLWithString:privacyIconImageUrl];
            MPURLRequest *imageRequest = [MPURLRequest requestWithURL:iconUrl];

            __weak __typeof__(self) weakSelf = self;
            [MPHTTPNetworkSession startTaskWithHttpRequest:imageRequest responseHandler:^(NSData * _Nonnull data, NSHTTPURLResponse * _Nonnull response) {
                // Cache the successfully retrieved icon image
                [MPMemoryCache.sharedInstance setData:data forKey:privacyIconImageUrl];

                // Populate the image view
                __typeof__(self) strongSelf = weakSelf;
                UIImageView *imageView = strongSelf.adView.nativePrivacyInformationIconImageView;
                imageView.hidden = NO;
                imageView.image = [UIImage imageWithData:data];

                // Attach a gesture recognizer to handle loading the privacy icon URL.
                UITapGestureRecognizer *tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:strongSelf action:@selector(onPrivacyIconTapped)];
                imageView.userInteractionEnabled = YES;
                [imageView addGestureRecognizer:tapRecognizer];
            } errorHandler:^(NSError * _Nonnull error) {
                MPLogInfo(@"Failed to retrieve privacy icon from %@", privacyIconImageUrl);
            }];
        }
        // The ad network may provide its own view for its privacy information icon.
        // We assume the ad handles the tap on the icon as well.
        else if ([adapter respondsToSelector:@selector(privacyInformationIconView)]) {
            UIView *privacyIconAdView = [adapter privacyInformationIconView];
            privacyIconAdView.frame = self.adView.nativePrivacyInformationIconImageView.bounds;
            privacyIconAdView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
            self.adView.nativePrivacyInformationIconImageView.userInteractionEnabled = YES;
            [self.adView.nativePrivacyInformationIconImageView addSubview:privacyIconAdView];
            self.adView.nativePrivacyInformationIconImageView.hidden = NO;
        }
        // No privacy icon
        else {
            self.adView.nativePrivacyInformationIconImageView.userInteractionEnabled = NO;
            self.adView.nativePrivacyInformationIconImageView.hidden = YES;
        }
    }
```

**Comment by chauduyphanvu1** [comment] 2018-11-29 17:02
@stuartbreckenridge - thanks for sending over the details. We'll take a look and get back to you. Do you still see this issue as of now?

**Comment by KevinTydlacka** [comment] 2019-01-02 20:40
Confirmed I also see the exact same behavior.

**Comment by chauduyphanvu1** [comment] 2019-01-02 20:46
@KevinTydlacka - thanks for letting us know! Do you have a reproducible sample app? Could you also confirm you've followed the instructions provided [here](https://developer.yahoo.com/flurry/docs/faq/faqpublisher/ios/#how-do-i-display-the-sponsored-icon-advertiser-name-when-mediating-native-ads-with-mopub) to add the Flurry sponsored icon?

**Comment by stuartbreckenridge** [comment] 2019-01-02 20:54
@chauduyphanvu1 Was there anything wrong with the sample app I provided? I never heard back on the issue.

**Comment by chauduyphanvu1** [comment] 2019-01-03 22:55
Closing due to expected behavior. Will update (via PRs) if this changes based on Flurry's plans.

**Closed by chauduyphanvu1** 2019-01-03 22:55 UTC
Labels: expected_behavior
