### ISSUE TITLE
facebook audience network memory increase

### ISSUE THREAD

**Issue by aiversonwk** [mopub/mopub-ios-mediation#120] opened 2018-11-22 14:26 UTC
Whenever I look at a video ad for fb, the memory will grow a bit until the app crashes.

**Comment by aiversonwk** [comment] 2018-11-29 04:00
Here is project https://drive.google.com/open?id=1g4W6V8FtmGi8C-mnrMeYCqKb-Ed9xppb
This project is used to demonstrate this problem. The ios project is in this path: frameworks/runtime-src/proj.ios_mac/mopub.xcworkspace. Click RunAD1 after running the demo. If the loading is successful, click PlayAD1. AD1 only plays Facebook ads, and each time an ad is played, the memory will grow, but it won't drop.

**Comment by chauduyphanvu1** [comment] 2018-12-03 22:44
Thanks for sending over the project, @aiversonwk! On iOS, we are using a web video player (rather than a native one) to play rewarded videos so I don't anticipate any stagnant cache or increased memory usage over time. At least memory should be released when you close the video player. Facebook might be using their own video player so it might present a different cause to the issue. 

Could you send over any kind of Instruments trace that shows this memory growth you are seeing? Thanks!

**Comment by chauduyphanvu1** [comment] 2018-12-11 21:39
Thanks for sending over the trace file. We'll try to reproduce it on our end. 

Does the memory go down/away when you close the page/ViewController (or navigate away from it)?

**Comment by chauduyphanvu1** [comment] 2018-12-21 15:39
There's work in progress to improve memory efficiency and avoid memory leaks. It should be addressed in a future SDK release. I'm closing this issue as a result of that.

For any publishers seeing ongoing memory growth when mediating another SDK, please reach out to that ad network directly for assistance. Thanks!

**Closed by chauduyphanvu1** 2018-12-21 15:39 UTC
Labels: help wanted

**Comment by yorkwang** [comment] 2019-03-21 03:20
Is it fixed now? I used the latest mopub sdk 5.6 and facebook sdk, same problem here. And I have tested that when calling facebook ads api directly, there is no memory leak. Only mopub + Facebook has this issue.

**Comment by yorkwang** [comment] 2019-03-21 03:31
`#pragma mark FBInterstitialAdDelegate methods

- (void)interstitialAdDidLoad:(FBInterstitialAd *)interstitialAd
{
    MPLogAdEvent([MPLogEvent adLoadSuccessForAdapter:NSStringFromClass(self.class)], self.fbPlacementId);
    [self.delegate interstitialCustomEvent:self didLoadAd:interstitialAd];
    
    // introduce timer for 1 hour per expiration logic introduced by FB
//    __weak __typeof__(self) weakSelf = self;
//    self.expirationTimer = [[MPRealTimeTimer alloc] initWithInterval:FB_ADS_EXPIRATION_INTERVAL block:^(MPRealTimeTimer *timer){
//        __strong __typeof__(weakSelf) strongSelf = weakSelf;
//        if (strongSelf && !strongSelf.hasTrackedImpression) {
//            [strongSelf.delegate interstitialCustomEventDidExpire:strongSelf];
//
//            NSError *error = [self createErrorWith:@"Facebook interstitial ad expired  per Audience Network's expiration policy"
//                                         andReason:@""
//                                     andSuggestion:@""];
//
//            MPLogAdEvent([MPLogEvent adShowFailedForAdapter:NSStringFromClass(self.class) error:error], self.fbPlacementId);
//            //Delete the cached objects
//            strongSelf.fbInterstitialAd = nil;
//        }
//        [strongSelf.expirationTimer invalidate];
//    }];
//    [self.expirationTimer scheduleNow];
}`

Just remove expirationTimer, the memory leak is gone. Hope it will help others.

**Comment by yorkwang** [comment] 2019-03-21 03:57
Add     self.expirationTimer = nil; like below will fix it too.
- (void)interstitialAdWillLogImpression:(FBInterstitialAd *)interstitialAd
{
    MPLogAdEvent([MPLogEvent adShowSuccessForAdapter:NSStringFromClass(self.class)], self.fbPlacementId);
    
    //set the tracker to true when the ad is shown on the screen. So that the timer is invalidated.
    _hasTrackedImpression = true;
    [self.delegate trackImpression];
    [self.expirationTimer invalidate];
    self.expirationTimer = nil;
}

**Comment by chauduyphanvu1** [comment] 2019-03-21 18:18
@yorkwang - thanks for doing the research and letting us know! Do you have any steps to reproduce that memory leak (as well as any traces of it)? If so, we can go ahead and validate them, and implement the fix.

**Comment by cunzhegao** [comment] 2019-03-29 06:34
@chauduyphanvu1 I'm seeing the same issue with rewarded video, this is the memory usage when i watched several facebook video ads in a row.
![before](https://user-images.githubusercontent.com/19347161/55213531-8e3f5800-522e-11e9-808f-e74ca246a80e.png)
Then i follow @yorkwang 's suggestion and set `expirationTimer = nil` in `rewardedVideoAdWillLogImpression:` callback. This is the memory usage i got after the change.
![after](https://user-images.githubusercontent.com/19347161/55213754-453bd380-522f-11e9-9478-3fec405647c4.png)
So it seems like that `expirationTimer` is holding a strong reference to `fbRewardedVideoAd`, resulting in memory not being released even after the ad was closed.

**Comment by chauduyphanvu1** [comment] 2019-04-01 21:09
@ cunzhegao, thanks for doing the research. We'll look into reproducing this leak and implementing an appropriate fix for the Facebook adapters. I'll ping this thread once the fix is live.

**Comment by chauduyphanvu1** [comment] 2019-04-09 21:04
This should have been addressed in https://github.com/mopub/mopub-ios-mediation/commit/f5ef0f25c77e8633bbeb968c8a42c53a92ee7d1b. Thanks, all, for the research and experiments to confirm the root cause of the issue! You should now see a more normal memory usage pattern with the new Facebook Audience Network adapters.
