### ISSUE TITLE
Raise architecture related warnings using with mopub 5.12.0

### ISSUE THREAD

**Issue by giginet** [mopub/mopub-ios-mediation#298] opened 2020-06-24 02:44 UTC
1. **What is the issue?**

I use 7.60.0.0 and MoPub 5.13.0 with CocoaPods. However, Xcode produces following warnings.

```
Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform.
Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform.
Mapping architecture armv7s to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform.
```

<img width="370" alt="Screen Shot 2020-06-24 at 11 38 14" src="https://user-images.githubusercontent.com/147051/85491867-39e07f00-b60f-11ea-98b9-e17615c8017e.png">

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        no
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.12.0 or above (this issue still caused on 5.13.0)
    * **Mediation SDK Name & Version**
        MoPub-AdMob-Adapters
    * **Mediation Adapter Version**
        7.60.0.0 
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        no
    * **Device model and OS Version**
        13.5
    * **Steps to reproduce the issue** (include integration steps if not standard)
        1. Create new iOS project on Xcode 11.5
        2. `pod init` and implement `Podfile` like below:
        3. `pod install`
        4. Build on Xcode

    * **Observed behavior**
raise warnings
    * **Expected behavior** (if known)
        Do not raise warnings
    * **Evidence** (if available)
        - Xcode 11.5
        - CocoaPods 1.9.3

I guess these warnings are caused by changes for `xcconfig` on mopub-ios-sdk on 5.12.0.

[Here](https://github.com/mopub/mopub-ios-sdk/compare/5.11.0...5.12.0#diff-c727b2f24d5914c3fba2a7371e8f2768R13-R15)

```ruby
target 'Mopub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mopub
  pod 'mopub-ios-sdk'
  pod 'MoPub-AdMob-Adapters'

end
```

**Comment by chauduyphanvu** [comment] 2020-06-25 18:24
@giginet, thanks for letting us know! This is a duplicate of https://github.com/mopub/mopub-ios-mediation/issues/274 and https://github.com/mopub/mopub-ios-mediation/issues/277. It isn't a fatal issue, and will not interfere with your ad logic. It might be due to the architecture of the simulator you are using—could you confirm if you also see the warnings on a physical iPhone?

Vu Chau
MoPub Team

**Comment by giginet** [comment] 2020-06-26 06:18
> It might be due to the architecture of the simulator you are using—

That's right. I'm using simulators.
Could you tell me the current workaround?

Thank you.

**Comment by chauduyphanvu** [comment] 2020-06-26 14:49
@giginet, here is the list of supported architectures by the AdMob SDK and adapters: https://github.com/CocoaPods/Specs/commit/dd11ed8216083e4e50c3c4f86217f0352c513955#diff-1e14c049b3f5e97a7950a3fc5bfb018cR23. 

Could you check on a device matching one of those supported architectures? Thanks!

**Comment by giginet** [comment] 2020-06-30 11:27
According to the Firebase AdMob release note, i386 support is already dropped. However, this mediation still supports i386 on simulators, so it still raises warnings.
https://github.com/CocoaPods/Specs/blob/master/Specs/9/3/7/MoPub-AdMob-Adapters/7.58.0.1/MoPub-AdMob-Adapters.podspec.json#L23

I guess `VALID_ARCHS` xcconfig may be like following:

```
"VALID_ARCHS[sdk=iphonesimulator*]": "x86_64"
```

I can't offer PR to podspecs.
Please confirm the podspec 🙏

**Comment by giginet** [comment] 2020-06-30 11:28
I added settings on the application side, Then the warnings can be suppressed.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # See https://github.com/mopub/mopub-ios-mediation/issues/277
      if %w[Pods-CookpadAdSDK Pods-CookpadAdSDK-CookpadAdSDKTests Pods-CookpadAdSDK-Example Pods-Mopub MoPub-AdMob-Adapters].include? target.to_s
        config.build_settings['VALID_ARCHS'] = ['arm64e arm64 armv7s armv7']
        config.build_settings["VALID_ARCHS[sdk=iphoneos*]"] = ['arm64 arm64e armv7 armv7s']
        config.build_settings["VALID_ARCHS[sdk=iphonesimulator*]"] = ['x86_64']
      end
    end
  end
end
```

**Comment by giginet** [comment] 2020-06-30 11:29
I added settings on the application side, Then the warnings can be suppressed.

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # See https://github.com/mopub/mopub-ios-mediation/issues/277
      if %w[Pods-Mopub MoPub-AdMob-Adapters].include? target.to_s
        config.build_settings['VALID_ARCHS'] = ['arm64e arm64 armv7s armv7']
        config.build_settings["VALID_ARCHS[sdk=iphoneos*]"] = ['arm64 arm64e armv7 armv7s']
        config.build_settings["VALID_ARCHS[sdk=iphonesimulator*]"] = ['x86_64']
      end
    end
  end
end
```

**Comment by carlosnaguilera** [comment] 2020-07-01 20:50
Same issue here. It would be great if you could do a new version removing the warnings. Apps empty of warning are easier to maintain! 😉

**Comment by chauduyphanvu** [comment] 2020-07-01 22:40
Hi all, this is now done in https://github.com/mopub/mopub-ios-mediation/commit/3116616580e9ea4d139f47d79b7c61ef08cb4e38 ([change](https://github.com/CocoaPods/Specs/commit/2ae97a8bd75fff484e8bfbaebc6f96e00ca9f9d9#diff-1993e629e1ed455ff6541eddb6e15a3cR24)).

Let us know if you have any questions!

**Closed by chauduyphanvu** 2020-07-01 22:40 UTC
Labels: EPSO-20200

**Comment by giginet** [comment] 2020-07-02 10:50
It works! Thanks.
